// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/rabbitmq/amqp091-go"
	"github.com/redis/go-redis/v9"
	"wex/api_service/src/controllers"
	"wex/api_service/src/core/ports"
	"wex/api_service/src/core/services"
	"wex/api_service/src/infra/dao"
	"wex/api_service/src/infra/repositories"
)

// Injectors from wire.go:

func InitializeAPI(db *sql.DB, amqpChannel *amqp091.Channel, redisClient *redis.Client, queue repositories.RabbitMQQueue, exchange repositories.RabbitMQExchange) *controllers.APIControllers {
	valkeyDAO := dao.NewValkeyDAO(redisClient)
	valkeyPayloadStore := repositories.NewValkeyPayloadStore(valkeyDAO)
	rabbitMQDAO := dao.NewRabbitMQDAO(amqpChannel)
	rabbitMQPublisher := repositories.NewRabbitMQPublisher(rabbitMQDAO, queue, exchange)
	transactionProducerService := services.NewTransactionProducerService(valkeyPayloadStore, rabbitMQPublisher)
	transactionController := controllers.NewTransactionController(transactionProducerService)
	conversionProducerService := services.NewConversionProducerService(valkeyPayloadStore, rabbitMQPublisher)
	conversionController := controllers.NewConversionController(conversionProducerService)
	apiControllers := controllers.NewAPIControllers(transactionController, conversionController)
	return apiControllers
}

// wire.go:

// ServiceSet defines the singleton services for the application.
var ServiceSet = wire.NewSet(services.NewTransactionProducerService, services.NewConversionProducerService)

// RepoSet defines the singleton repositories.
var RepoSet = wire.NewSet(repositories.NewValkeyPayloadStore, wire.Bind(new(ports.PayloadStore), new(*repositories.ValkeyPayloadStore)), repositories.NewRabbitMQPublisher, wire.Bind(new(ports.MessagePublisher), new(*repositories.RabbitMQPublisher)))

// DAOSet defines the singleton DAOs.
var DAOSet = wire.NewSet(dao.NewValkeyDAO, dao.NewRabbitMQDAO, wire.Bind(new(repositories.RabbitMQPublisherDAO), new(*dao.RabbitMQDAO)), wire.Bind(new(repositories.ValkeyDAO), new(*dao.ValkeyDAO)))
