version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:latest
    command: valkey-server --port ${VALKEY_PORT}
    ports:
      - "${VALKEY_PORT}:${VALKEY_PORT}"
    healthcheck:
      test: [ "CMD", "valkey-cli", "-p", "${VALKEY_PORT}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_NODE_PORT: ${RABBITMQ_PORT}
      RABBITMQ_MANAGEMENT_LISTENER_PORT: ${RABBITMQ_MANAGEMENT_PORT}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 10s
      retries: 5

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  api-service:
    build: ./api_service
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      valkey:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully

  transaction-service:
    build: ./transaction_service
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      valkey:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully

  conversion-service:
    build: ./conversion_service
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      valkey:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
