// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/rabbitmq/amqp091-go"
	"github.com/redis/go-redis/v9"
	"wex/conversion_service/src/core/ports"
	"wex/conversion_service/src/core/services"
	"wex/conversion_service/src/infra"
	"wex/conversion_service/src/infra/dao"
	"wex/conversion_service/src/infra/repositories"
)

// Injectors from wire.go:

func InitializeWorker(db *sql.DB, amqpChannel *amqp091.Channel, redisClient *redis.Client, queueName string) *infra.RabbitMQConsumer {
	postgresDAO := dao.NewPostgresDAO(db)
	transactionRepository := repositories.NewTransactionRepository(postgresDAO)
	treasuryAPIDAO := dao.NewTreasuryAPIDAO()
	treasuryRateProvider := repositories.NewTreasuryRateProvider(treasuryAPIDAO)
	transactionQueryService := services.NewTransactionQueryService(transactionRepository, treasuryRateProvider)
	valkeyDAO := dao.NewValkeyDAO(redisClient)
	valkeyPayloadStore := repositories.NewValkeyPayloadStore(valkeyDAO)
	rabbitMQConsumer := infra.NewRabbitMQConsumer(amqpChannel, queueName, transactionQueryService, valkeyPayloadStore)
	return rabbitMQConsumer
}

// wire.go:

// ServiceSet defines the singleton services for the application.
var ServiceSet = wire.NewSet(services.NewTransactionQueryService)

// RepoSet defines the singleton repositories.
var RepoSet = wire.NewSet(repositories.NewTransactionRepository, wire.Bind(new(ports.TransactionRepository), new(*repositories.TransactionRepository)), repositories.NewTreasuryRateProvider, wire.Bind(new(ports.ConversionRateProvider), new(*repositories.TreasuryRateProvider)), repositories.NewValkeyPayloadStore, wire.Bind(new(ports.PayloadStore), new(*repositories.ValkeyPayloadStore)))

// DAOSet defines the singleton DAOs.
var DAOSet = wire.NewSet(dao.NewPostgresDAO, dao.NewTreasuryAPIDAO, dao.NewValkeyDAO)
