// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/rabbitmq/amqp091-go"
	"github.com/redis/go-redis/v9"
	"wex/conversion_service/src/core/ports"
	"wex/conversion_service/src/core/services"
	"wex/conversion_service/src/infra"
	"wex/conversion_service/src/infra/dao"
	"wex/conversion_service/src/infra/providers"
	"wex/conversion_service/src/infra/repositories"
)

// Injectors from wire.go:

func InitializeWorker(db *sql.DB, amqpChannel *amqp091.Channel, redisClient *redis.Client, queueName string) *infra.RabbitMQConsumer {
	postgresDAO := dao.NewPostgresDAO(db)
	transactionRepository := repositories.NewTransactionRepository(postgresDAO)
	treasuryAPIDAO := dao.NewTreasuryAPIDAO()
	treasuryRateRepository := repositories.NewTreasuryRateRepository(treasuryAPIDAO)
	ratePostgresRepository := repositories.NewRatePostgresRepository(postgresDAO)
	valkeyDAO := dao.NewValkeyDAO(redisClient)
	valkeyRepository := repositories.NewValkeyRepository(valkeyDAO)
	rateCacheProvider := providers.NewRateCacheProvider(treasuryRateRepository, ratePostgresRepository, valkeyRepository)
	conversionService := services.NewConversionService(transactionRepository, rateCacheProvider, valkeyRepository)
	rabbitMQConsumer := infra.NewRabbitMQConsumer(amqpChannel, queueName, conversionService, valkeyRepository)
	return rabbitMQConsumer
}

// wire.go:

// ServiceSet defines the singleton services for the application.
var ServiceSet = wire.NewSet(services.NewConversionService)

// RepoSet defines the singleton repositories.
var RepoSet = wire.NewSet(repositories.NewTransactionRepository, wire.Bind(new(ports.TransactionRepository), new(*repositories.TransactionRepository)), repositories.NewTreasuryRateRepository, repositories.NewRatePostgresRepository, providers.NewRateCacheProvider, wire.Bind(new(ports.ConversionRateProvider), new(*providers.RateCacheProvider)), repositories.NewValkeyRepository, wire.Bind(new(ports.PayloadStore), new(*repositories.ValkeyRepository)))

// DAOSet defines the singleton DAOs.
var DAOSet = wire.NewSet(dao.NewPostgresDAO, wire.Bind(new(repositories.RatePostgresDAO), new(*dao.PostgresDAO)), wire.Bind(new(repositories.PostgresDAO), new(*dao.PostgresDAO)), dao.NewTreasuryAPIDAO, wire.Bind(new(repositories.TreasuryAPIDAO), new(*dao.TreasuryAPIDAO)), dao.NewValkeyDAO, wire.Bind(new(repositories.ValkeyDAO), new(*dao.ValkeyDAO)))
